[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'

[pve]
pve01.mgmt.etsmtl.club ansible_host=10.0.21.51
pve02.mgmt.etsmtl.club ansible_host=10.0.21.52
pve03.mgmt.etsmtl.club ansible_host=10.0.21.53
pve04.mgmt.etsmtl.club ansible_host=10.0.21.54
pve05.mgmt.etsmtl.club ansible_host=10.0.21.55
pve06.mgmt.etsmtl.club ansible_host=10.0.21.56
pve07.mgmt.etsmtl.club ansible_host=10.0.21.57
pve08.mgmt.etsmtl.club ansible_host=10.0.21.58

[shellctf]
shellctf01.mgmt.etsmtl.club ansible_host=10.140.0.101
shellctf02.mgmt.etsmtl.club ansible_host=10.140.0.102
shellctf03.mgmt.etsmtl.club ansible_host=10.140.0.103
shellctf04.mgmt.etsmtl.club ansible_host=10.140.0.104
shellctf05.mgmt.etsmtl.club ansible_host=10.140.0.105
shellctf06.mgmt.etsmtl.club ansible_host=10.140.0.106
shellctf07.mgmt.etsmtl.club ansible_host=10.140.0.107
shellctf08.mgmt.etsmtl.club ansible_host=10.140.0.108
shellctf09.mgmt.etsmtl.club ansible_host=10.140.0.109
shellctf10.mgmt.etsmtl.club ansible_host=10.140.0.110
shellctf11.mgmt.etsmtl.club ansible_host=10.140.0.111
shellctf12.mgmt.etsmtl.club ansible_host=10.140.0.112
shellctf13.mgmt.etsmtl.club ansible_host=10.140.0.113
shellctf14.mgmt.etsmtl.club ansible_host=10.140.0.114
shellctf15.mgmt.etsmtl.club ansible_host=10.140.0.115
shellctf16.mgmt.etsmtl.club ansible_host=10.140.0.116
shellctf17.mgmt.etsmtl.club ansible_host=10.140.0.117
shellctf18.mgmt.etsmtl.club ansible_host=10.140.0.118
shellctf19.mgmt.etsmtl.club ansible_host=10.140.0.119
shellctf20.mgmt.etsmtl.club ansible_host=10.140.0.120
shellctf21.mgmt.etsmtl.club ansible_host=10.140.0.121
shellctf22.mgmt.etsmtl.club ansible_host=10.140.0.122
shellctf23.mgmt.etsmtl.club ansible_host=10.140.0.123
shellctf24.mgmt.etsmtl.club ansible_host=10.140.0.124
shellctf25.mgmt.etsmtl.club ansible_host=10.140.0.125
shellctf26.mgmt.etsmtl.club ansible_host=10.140.0.126
shellctf27.mgmt.etsmtl.club ansible_host=10.140.0.127
shellctf28.mgmt.etsmtl.club ansible_host=10.140.0.128
shellctf29.mgmt.etsmtl.club ansible_host=10.140.0.129
shellctf30.mgmt.etsmtl.club ansible_host=10.140.0.130
shellctf31.mgmt.etsmtl.club ansible_host=10.140.0.131
shellctf32.mgmt.etsmtl.club ansible_host=10.140.0.132
shellctf33.mgmt.etsmtl.club ansible_host=10.140.0.133
shellctf34.mgmt.etsmtl.club ansible_host=10.140.0.134
shellctf35.mgmt.etsmtl.club ansible_host=10.140.0.135
shellctf36.mgmt.etsmtl.club ansible_host=10.140.0.136
shellctf37.mgmt.etsmtl.club ansible_host=10.140.0.137
shellctf38.mgmt.etsmtl.club ansible_host=10.140.0.138
shellctf39.mgmt.etsmtl.club ansible_host=10.140.0.139
shellctf40.mgmt.etsmtl.club ansible_host=10.140.0.140
shellctf41.mgmt.etsmtl.club ansible_host=10.140.0.141
shellctf42.mgmt.etsmtl.club ansible_host=10.140.0.142
shellctf43.mgmt.etsmtl.club ansible_host=10.140.0.143
shellctf44.mgmt.etsmtl.club ansible_host=10.140.0.144
shellctf45.mgmt.etsmtl.club ansible_host=10.140.0.145
shellctf46.mgmt.etsmtl.club ansible_host=10.140.0.146
shellctf47.mgmt.etsmtl.club ansible_host=10.140.0.147
shellctf48.mgmt.etsmtl.club ansible_host=10.140.0.148
shellctf49.mgmt.etsmtl.club ansible_host=10.140.0.149
shellctf50.mgmt.etsmtl.club ansible_host=10.140.0.150
