[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'

[pve]
pve01.mgmt.etsmtl.club ansible_host=10.0.21.51
pve02.mgmt.etsmtl.club ansible_host=10.0.21.52
pve03.mgmt.etsmtl.club ansible_host=10.0.21.53
pve04.mgmt.etsmtl.club ansible_host=10.0.21.54
pve05.mgmt.etsmtl.club ansible_host=10.0.21.55
pve06.mgmt.etsmtl.club ansible_host=10.0.21.56
pve07.mgmt.etsmtl.club ansible_host=10.0.21.57
pve08.mgmt.etsmtl.club ansible_host=10.0.21.58

[shellctf]
shellctf01.mgmt.etsmtl.club ansible_host=10.140.0.101 vm_id=811101
shellctf02.mgmt.etsmtl.club ansible_host=10.140.0.102 vm_id=811102
shellctf03.mgmt.etsmtl.club ansible_host=10.140.0.103 vm_id=811103
shellctf04.mgmt.etsmtl.club ansible_host=10.140.0.104 vm_id=811104
shellctf05.mgmt.etsmtl.club ansible_host=10.140.0.105 vm_id=811105
shellctf06.mgmt.etsmtl.club ansible_host=10.140.0.106 vm_id=811106
shellctf07.mgmt.etsmtl.club ansible_host=10.140.0.107 vm_id=811107
shellctf08.mgmt.etsmtl.club ansible_host=10.140.0.108 vm_id=811108
shellctf09.mgmt.etsmtl.club ansible_host=10.140.0.109 vm_id=811109
shellctf10.mgmt.etsmtl.club ansible_host=10.140.0.110 vm_id=811110
shellctf11.mgmt.etsmtl.club ansible_host=10.140.0.111 vm_id=811111
shellctf12.mgmt.etsmtl.club ansible_host=10.140.0.112 vm_id=811112
shellctf13.mgmt.etsmtl.club ansible_host=10.140.0.113 vm_id=811113
shellctf14.mgmt.etsmtl.club ansible_host=10.140.0.114 vm_id=811114
shellctf15.mgmt.etsmtl.club ansible_host=10.140.0.115 vm_id=811115
shellctf16.mgmt.etsmtl.club ansible_host=10.140.0.116 vm_id=811116
shellctf17.mgmt.etsmtl.club ansible_host=10.140.0.117 vm_id=811117
shellctf18.mgmt.etsmtl.club ansible_host=10.140.0.118 vm_id=811118
shellctf19.mgmt.etsmtl.club ansible_host=10.140.0.119 vm_id=811119
shellctf20.mgmt.etsmtl.club ansible_host=10.140.0.120 vm_id=811120
shellctf21.mgmt.etsmtl.club ansible_host=10.140.0.121 vm_id=811121
shellctf22.mgmt.etsmtl.club ansible_host=10.140.0.122 vm_id=811122
shellctf23.mgmt.etsmtl.club ansible_host=10.140.0.123 vm_id=811123
shellctf24.mgmt.etsmtl.club ansible_host=10.140.0.124 vm_id=811124
shellctf25.mgmt.etsmtl.club ansible_host=10.140.0.125 vm_id=811125
shellctf26.mgmt.etsmtl.club ansible_host=10.140.0.126 vm_id=811126
shellctf27.mgmt.etsmtl.club ansible_host=10.140.0.127 vm_id=811127
shellctf28.mgmt.etsmtl.club ansible_host=10.140.0.128 vm_id=811128
shellctf29.mgmt.etsmtl.club ansible_host=10.140.0.129 vm_id=811129
shellctf30.mgmt.etsmtl.club ansible_host=10.140.0.130 vm_id=811130
shellctf31.mgmt.etsmtl.club ansible_host=10.140.0.131 vm_id=811131
shellctf32.mgmt.etsmtl.club ansible_host=10.140.0.132 vm_id=811132
shellctf33.mgmt.etsmtl.club ansible_host=10.140.0.133 vm_id=811133
shellctf34.mgmt.etsmtl.club ansible_host=10.140.0.134 vm_id=811134
shellctf35.mgmt.etsmtl.club ansible_host=10.140.0.135 vm_id=811135
shellctf36.mgmt.etsmtl.club ansible_host=10.140.0.136 vm_id=811136
shellctf37.mgmt.etsmtl.club ansible_host=10.140.0.137 vm_id=811137
shellctf38.mgmt.etsmtl.club ansible_host=10.140.0.138 vm_id=811138
shellctf39.mgmt.etsmtl.club ansible_host=10.140.0.139 vm_id=811139
shellctf40.mgmt.etsmtl.club ansible_host=10.140.0.140 vm_id=811140
shellctf41.mgmt.etsmtl.club ansible_host=10.140.0.141 vm_id=811141
shellctf42.mgmt.etsmtl.club ansible_host=10.140.0.142 vm_id=811142
shellctf43.mgmt.etsmtl.club ansible_host=10.140.0.143 vm_id=811143
shellctf44.mgmt.etsmtl.club ansible_host=10.140.0.144 vm_id=811144
shellctf45.mgmt.etsmtl.club ansible_host=10.140.0.145 vm_id=811145
shellctf46.mgmt.etsmtl.club ansible_host=10.140.0.146 vm_id=811146
shellctf47.mgmt.etsmtl.club ansible_host=10.140.0.147 vm_id=811147
shellctf48.mgmt.etsmtl.club ansible_host=10.140.0.148 vm_id=811148
shellctf49.mgmt.etsmtl.club ansible_host=10.140.0.149 vm_id=811149
shellctf50.mgmt.etsmtl.club ansible_host=10.140.0.150 vm_id=811150
