[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[pve]
pve01.mgmt.etsmtl.club ansible_host=10.0.21.51
pve02.mgmt.etsmtl.club ansible_host=10.0.21.52
pve03.mgmt.etsmtl.club ansible_host=10.0.21.53
pve04.mgmt.etsmtl.club ansible_host=10.0.21.54
pve05.mgmt.etsmtl.club ansible_host=10.0.21.55
pve06.mgmt.etsmtl.club ansible_host=10.0.21.56
pve07.mgmt.etsmtl.club ansible_host=10.0.21.57
pve08.mgmt.etsmtl.club ansible_host=10.0.21.58

[ipmi:children]
ilo
idrac

[ilo]
pve01.ipmi.etsmtl.club ansible_host=10.0.21.41
pve02.ipmi.etsmtl.club ansible_host=10.0.21.42
pve03.ipmi.etsmtl.club ansible_host=10.0.21.43
pve04.ipmi.etsmtl.club ansible_host=10.0.21.44
pve07.ipmi.etsmtl.club ansible_host=10.0.21.47

[idrac]
pve05.ipmi.etsmtl.club ansible_host=10.0.21.45
pve06.ipmi.etsmtl.club ansible_host=10.0.21.46
pve08.ipmi.etsmtl.club ansible_host=10.0.21.48

[nas]
nas01.mgmt.etsmtl.club ansible_host=10.0.21.50 ansible_user=localadmin

[ipmi]
nasmgmt01.ipmi.etsmtl.club ansible_host=10.0.21.91

[routers]
opnsense01.prod.etsmtl.club ansible_host=10.0.21.2
opnsense02.prod.etsmtl.club ansible_host=10.0.21.3

[switches:children]
nxos
; ios

[nxos]
data01.mgmt.etsmtl.club ansible_host=10.0.21.11

; [ios]
; axs01.mgmt.etsmtl.club ansible_host=10.0.21.31
; mgmt01.mgmt.etsmtl.club ansible_host=10.0.21.32

[pnp-server]
pnp01.mgmt.etsmtl.club ansible_host=10.0.21.81

[netservices_dhcp]
dhcp01.mgmt.etsmtl.club ansible_host=10.0.21.17 vm_id=500117
dhcp02.mgmt.etsmtl.club ansible_host=10.0.21.18 vm_id=500118

[omni]
omni01.prod.etsmtl.club ansible_host=142.137.247.99

[monitoring_core]
monitoring01.mgmt.etsmtl.club ansible_host=10.0.21.95

[monitoring_exporters:children]
monitoring_core

[monitoring_node_exporter:children]
pve
nas

[monitoring_alloy:children]
pve
nas

[k8s_poc_controlplanes]
k8s-poc-controlplane01.k8s.etsmtl.club ansible_host=10.0.130.11
k8s-poc-controlplane02.k8s.etsmtl.club ansible_host=10.0.130.12
k8s-poc-controlplane03.k8s.etsmtl.club ansible_host=10.0.130.13
k8s-poc-controlplane04.k8s.etsmtl.club ansible_host=10.0.130.14
k8s-poc-controlplane05.k8s.etsmtl.club ansible_host=10.0.130.15

[k8s_poc_workers]
k8s-poc-worker01.k8s.etsmtl.club ansible_host=10.0.130.21
k8s-poc-worker02.k8s.etsmtl.club ansible_host=10.0.130.22
k8s-poc-worker03.k8s.etsmtl.club ansible_host=10.0.130.23
k8s-poc-worker04.k8s.etsmtl.club ansible_host=10.0.130.24
k8s-poc-worker05.k8s.etsmtl.club ansible_host=10.0.130.25
k8s-poc-worker06.k8s.etsmtl.club ansible_host=10.0.130.26
k8s-poc-worker07.k8s.etsmtl.club ansible_host=10.0.130.27
k8s-poc-worker08.k8s.etsmtl.club ansible_host=10.0.130.28

[k8s_poc_dhcp]
dhcp01.k8s.etsmtl.club ansible_host=10.0.130.31 vm_id=1300031
dhcp02.k8s.etsmtl.club ansible_host=10.0.130.32 vm_id=1300032

[k8s_poc:children]
k8s_poc_controlplanes
k8s_poc_workers

[vlan66_dhcp]
dhcp01.lanets.etsmtl.club ansible_host=10.66.0.31 vm_id=66031
dhcp02.lanets.etsmtl.club ansible_host=10.66.0.32 vm_id=66032

[forgejo_runners]
forgejo-runner01.mgmt.etsmtl.club ansible_host=10.0.21.236 vm_id=21236
forgejo-runner02.mgmt.etsmtl.club ansible_host=10.0.21.237 vm_id=21237

# DCI VMs de pratique
[dci_vms]
pratique01.dci.etsmtl.club ansible_host=10.68.1.101 vm_id=821101
pratique02.dci.etsmtl.club ansible_host=10.68.1.102 vm_id=821102
pratique03.dci.etsmtl.club ansible_host=10.68.1.103 vm_id=821103

