[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[pve]
pve01.mgmt.etsmtl.club ansible_host=10.0.21.51
pve02.mgmt.etsmtl.club ansible_host=10.0.21.52
pve03.mgmt.etsmtl.club ansible_host=10.0.21.53
pve04.mgmt.etsmtl.club ansible_host=10.0.21.54
pve05.mgmt.etsmtl.club ansible_host=10.0.21.55
pve06.mgmt.etsmtl.club ansible_host=10.0.21.56
pve07.mgmt.etsmtl.club ansible_host=10.0.21.57
pve08.mgmt.etsmtl.club ansible_host=10.0.21.58

[ipmi:children]
ilo
idrac

[ilo]
pve01.ipmi.etsmtl.club ansible_host=10.0.21.41
pve02.ipmi.etsmtl.club ansible_host=10.0.21.42
pve03.ipmi.etsmtl.club ansible_host=10.0.21.43
pve04.ipmi.etsmtl.club ansible_host=10.0.21.44
pve07.ipmi.etsmtl.club ansible_host=10.0.21.47

[idrac]
pve05.ipmi.etsmtl.club ansible_host=10.0.21.45
pve06.ipmi.etsmtl.club ansible_host=10.0.21.46
pve08.ipmi.etsmtl.club ansible_host=10.0.21.48

[nas]
nas01.mgmt.etsmtl.club ansible_host=10.0.21.50 ansible_user=localadmin

[ipmi]
nasmgmt01.ipmi.etsmtl.club ansible_host=10.0.21.91

[routers]
opnsense01.prod.etsmtl.club ansible_host=10.0.21.2
opnsense02.prod.etsmtl.club ansible_host=10.0.21.3

[switches:children]
nxos
; ios

[nxos]
data01.mgmt.etsmtl.club ansible_host=10.0.21.11

; [ios]
; axs01.mgmt.etsmtl.club ansible_host=10.0.21.31
; mgmt01.mgmt.etsmtl.club ansible_host=10.0.21.32

[pnp-server]
pnp01.mgmt.etsmtl.club ansible_host=10.0.21.81

[netservices_dhcp]
dhcp01.mgmt.etsmtl.club ansible_host=10.0.21.17 vm_id=500117
dhcp02.mgmt.etsmtl.club ansible_host=10.0.21.18 vm_id=500118

[monitoring_core]
monitoring01.mgmt.etsmtl.club ansible_host=10.0.21.95

[monitoring_exporters:children]
monitoring_core

[monitoring_node_exporter:children]
pve
nas

[monitoring_alloy:children]
pve
nas
