---
# Overrides spécifiques aux 5 control-planes de k8s-shared (vérifié via pvesh le
# 2026-08-17) : disque unique "scsi0" (40G, virtio-scsi), 2 NICs (pas d'IP publique,
# contrairement aux workers).
vm_disk_device: scsi0
vm_disk_size: 40G
vm_scsihw: virtio-scsi-pci

vm_tags:
  - "PRODUCTION"
  - "SHARED"
  - "CONTROLPLANE"
  - "TF"
  - "K8S-SHARED"
