---
ansible_user: localadmin

vm_cpu_cores: 2
vm_memory_mb: 2048
vm_disk_size: "20G"

vm_disk_image_path: "/var/lib/vz/images/lanets/ubuntu_2404.img"
vm_disk_storage: "RBD_Common"
vm_disk_format: "raw"
vm_disk_device: "virtio0"
vm_cloud_init_storage: "RBD_Common"

vm_delete_if_exists: false
vm_start_after_creation: true
vm_onboot: true

vm_name: "{{ inventory_hostname }}"
vm_proxmox_node: "{{ 'pve01' if inventory_hostname.startswith('dhcp01') else 'pve02' }}"

vm_net:
  bridge: "vmbr1"
  vlan: "21"
  device: virtio
  ip: "{{ ansible_host }}"
  netmask: "24"
  gateway: "10.0.21.1"
  nameservers: "1.1.1.1,8.8.8.8"
  search_domain: "mgmt.etsmtl.club"

vm_proxmox_api:
  user: "root@pam"
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    38616663323566326538653235663137303731356666336338303339616164366637373438663366
    3664396432356165363735646236376238633331373332300a356532353031656264333035303939
    61653665626562323564346563336463393633663231653063616566353961353434363338353531
    6333623135383336610a343532623531353331643164353261666333663637643437383861373161
    3564
  host: "10.0.21.51"

netservices_dhcp:
  enabled: true
  supported_distribution: Ubuntu
  supported_distribution_version: "24.04"

  install:
    update_cache: true
    package_state: present
    packages:
      - kea-dhcp4-server
      - kea-ctrl-agent

  service:
    dhcp4_name: kea-dhcp4-server
    ctrl_agent_name: kea-ctrl-agent
    state: started
    enabled: true

  paths:
    dhcp4_config: /etc/kea/kea-dhcp4.conf
    ctrl_agent_config: /etc/kea/kea-ctrl-agent.conf
    dhcp4_control_socket: /run/kea/kea4-ctrl-socket

  ha:
    enabled: true
    mode: hot-standby
    this_server_name: "{{ 'primary' if inventory_hostname.startswith('dhcp01') else 'standby' }}"
    heartbeat_delay: 10000
    max_response_delay: 60000
    max_ack_delay: 5000
    max_unacked_clients: 10
    sync_page_limit: 10000
    primary:
      name: primary
      url: "http://10.0.21.17:8000/"
    standby:
      name: standby
      url: "http://10.0.21.18:8000/"

  client_classes: []
  extra_hook_libraries: []

  kea_dhcp4_config:
    Dhcp4:
      interfaces-config:
        interfaces:
          - "*"
      control-socket:
        socket-type: unix
        socket-name: /run/kea/kea4-ctrl-socket
      lease-database:
        type: memfile
        persist: true
        name: /var/lib/kea/kea-leases4.csv
      valid-lifetime: 4000
      renew-timer: 1000
      rebind-timer: 2000
      subnet4:
        - subnet: "10.0.21.0/24"
          id: 21
          pools:
            - pool: "10.0.21.151 - 10.0.21.200"
          option-data:
            - name: routers
              data: "10.0.21.1"
            - name: domain-name-servers
              data: "1.1.1.1,8.8.8.8"
      option-data: []
      hooks-libraries:
        - library: /usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_lease_cmds.so
        - library: /usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_ha.so
          parameters:
            high-availability:
              - this-server-name: "{{ 'primary' if inventory_hostname.startswith('dhcp01') else 'standby' }}"
                mode: hot-standby
                heartbeat-delay: 10000
                max-response-delay: 60000
                max-ack-delay: 5000
                max-unacked-clients: 10
                sync-page-limit: 10000
                peers:
                  - name: primary
                    url: "http://10.0.21.17:8000/"
                    role: primary
                    auto-failover: true
                  - name: standby
                    url: "http://10.0.21.18:8000/"
                    role: standby
                    auto-failover: true
      loggers:
        - name: kea-dhcp4
          output_options:
            - output: stdout
          severity: INFO

  kea_ctrl_agent_config:
    Control-agent:
      http-host: 0.0.0.0
      http-port: 8000
      control-sockets:
        dhcp4:
          socket-type: unix
          socket-name: /run/kea/kea4-ctrl-socket
