---

ansible_host: 10.0.21.81
ansible_user: localadmin
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35653565353663656433343433616431623466366338616537616435336232343062363536613761
          6633303438653737353263653931323531666538663066620a636461316130363830633231383137
          66363732306439666164316436376535653438303161326166393131663136653632393731666233
          3034303865643139380a373933343831663134663065626664333735626361373330363536623265
          6466


pnp_server_http:
  docroot: /var/www/cisco-pnp
  device_map_path: /var/lib/cisco-pnp/device-map.yaml
  profiles_src_dir: /var/lib/cisco-pnp/profiles
  public_host: "{{ ansible_default_ipv4.address }}"
  image_url: "http://{{ pnp_server_http.public_host }}:{{ pnp_server_http.listen.port }}/images"
  config_url: "http://{{ pnp_server_http.public_host }}:{{ pnp_server_http.listen.port }}/configs"
  listen:
    address: "0.0.0.0"
    port: 8080
  install_nginx: true
  nginx_service_name: nginx

pnp_server_day0:
  profiles_source_group: cisco_bootstrapped
  devices_source_group: cisco_bootstrapped
  require_identifier: true
  validate_unique_serial: true
  validate_unique_mac: true
  mgmt_svi_vlan_id: 100

  site:
    domain_name: pnp01.mgmt.etsmtl.club
    name_servers:
      - 1.1.1.1
      - 8.8.8.8
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org

  profiles:
    - name: sw01
      hostname: sw01.etsmtl.club
      admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35653565353663656433343433616431623466366338616537616435336232343062363536613761
          6633303438653737353263653931323531666538663066620a636461316130363830633231383137
          66363732306439666164316436376535653438303161326166393131663136653632393731666233
          3034303865643139380a373933343831663134663065626664333735626361373330363536623265
          6466
      description: Switch 01
      mgmt_default_gateway: 10.0.21.1

  devices:
    - profile: sw01
      mac: 6C:99:89:73:64:00
      serial: FOC1801U0EQ

pnp_server_backend:
  enabled: true
  bind:
    address: "127.0.0.1"
    port: 9191
  base_dir: /var/lib/cisco-pnp
  bundle_dir: "{{ pnp_server_backend.base_dir }}/pnp"
  git:
    repo: https://github.com/GreatSymphonia/pnp-server.git
    version: main
    checkout_dir: "{{ pnp_server_backend.base_dir }}/src/pnp-server"
  user: pnp
  group: pnp
  venv_dir: "{{ pnp_server_backend.base_dir }}/venv"
  log_dir: "{{ pnp_server_backend.base_dir }}/log"
  log_file: "{{ pnp_server_backend.log_dir }}/pnp_debug.log"
  script_path: "{{ pnp_server_backend.bundle_dir }}/open-pnp.py"
  config_path: "{{ pnp_server_backend.bundle_dir }}/open-pnp.toml"
  images_path: "{{ pnp_server_backend.bundle_dir }}/images.toml"
  service_name: pnp-server
  pip_packages:
    - flask
    - xmltodict
    - requests
    - ifaddr
    - tomli

pnp_server_tls:
  enabled: false
  selfsigned: false
  days: 3650
  cert: /etc/nginx/certs/cisco-pnp.crt
  key: /etc/nginx/certs/cisco-pnp.key
