#!/usr/bin/env python3
"""Regenerate inventories/summercamp/hosts.ini from data/raw/passwords.csv.

Challenge columns are auto-detected as every column after 'password'.
Challenge index (1-based, left-to-right) drives IP subnet and vm_id:
  ansible_host = 10.130.{(n-1)*2}.{100+team}
  vm_id        = 2000000 + n*1000 + 100 + team
"""

import csv
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = REPO_ROOT / "data/raw/passwords.csv"
INVENTORY_PATH = REPO_ROOT / "inventories/summercamp/hosts.ini"

SHELLCTF_COUNT = 50

STATIC_SECTIONS = """\
[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'

[pve]
pve01.mgmt.etsmtl.club ansible_host=10.0.21.51
pve02.mgmt.etsmtl.club ansible_host=10.0.21.52
pve03.mgmt.etsmtl.club ansible_host=10.0.21.53
pve04.mgmt.etsmtl.club ansible_host=10.0.21.54
pve05.mgmt.etsmtl.club ansible_host=10.0.21.55
pve06.mgmt.etsmtl.club ansible_host=10.0.21.56
pve07.mgmt.etsmtl.club ansible_host=10.0.21.57
pve08.mgmt.etsmtl.club ansible_host=10.0.21.58

[dockercache]
dockercache01.camp ansible_host=10.150.0.100 vm_id=812101

[ctfd]
ctfd.summercamp.dciets.com ansible_host=142.137.247.107
"""

NETSERVICES_DNS_SECTION = """\
[netservices_dns]
dns01.camp ansible_host=10.130.0.21 vm_id=814101
dns02.camp ansible_host=10.130.0.22 vm_id=814102
"""


def build_shellctf_section(count: int) -> str:
    lines = ["[shellctf]"]
    for i in range(1, count + 1):
        lines.append(
            f"shell{i:02d}.ctf ansible_host=10.140.0.{100 + i} vm_id=811{100 + i}"
        )
    return "\n".join(lines)


def build_challenge_section(challenge: str, chall_idx: int, teams: list[dict]) -> str:
    lines = [f"[{challenge}]"]
    for row in teams:
        team = int(row["team"])
        hash_val = row[challenge]
        ip = f"10.130.{(chall_idx - 1) * 2}.{100 + team}"
        vm_id = 2000000 + chall_idx * 1000 + 100 + team
        lines.append(
            f"{hash_val}-{challenge}.ctf ansible_host={ip} vm_id={vm_id}"
        )
    return "\n".join(lines)


def main() -> None:
    with CSV_PATH.open(newline="") as f:
        reader = csv.DictReader(f)
        teams = list(reader)

    fieldnames = reader.fieldnames or []
    # Challenges are every column after 'password'
    password_idx = fieldnames.index("password")
    challenges = fieldnames[password_idx + 1:]

    sections = [
        "# Generated by scripts/gen_inventory.py — do not edit manually",
        "",
        STATIC_SECTIONS,
        build_shellctf_section(SHELLCTF_COUNT),
        "",
        NETSERVICES_DNS_SECTION,
    ]

    for idx, challenge in enumerate(challenges, start=1):
        sections.append(build_challenge_section(challenge, idx, teams))
        sections.append("")

    chall_children = "[chall:children]\n" + "\n".join(challenges)
    sections.append(chall_children)
    sections.append("")

    INVENTORY_PATH.write_text("\n".join(sections))
    print(f"Wrote {INVENTORY_PATH}")
    print(f"Challenges: {', '.join(f'{c} (idx={i})' for i, c in enumerate(challenges, 1))}")
    print(f"Teams: {len(teams)}")


if __name__ == "__main__":
    main()
