[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'

[netservices_dhcp]
dhcp01.event.etsmtl.club ansible_host=10.10.0.11
dhcp02.event.etsmtl.club ansible_host=10.10.0.12

[netservices_dns]
dns01.event.etsmtl.club ansible_host=10.10.0.21
dns02.event.etsmtl.club ansible_host=10.10.0.22

[netservices_stork]
stork01.event.etsmtl.club ansible_host=10.10.0.31
