[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'

# VIP on .1
[opnsense]
opnsense01.event.lanets.ca ansible_host=10.10.0.2
opnsense02.event.lanets.ca ansible_host=10.10.0.3

[netservices_dhcp]
dhcp01.event.lanets.ca ansible_host=10.10.0.11
dhcp02.event.lanets.ca ansible_host=10.10.0.12

[netservices_dns]
dns01.event.lanets.ca ansible_host=10.10.0.21
dns02.event.lanets.ca ansible_host=10.10.0.22

[netservices_stork]
stork01.event.lanets.ca ansible_host=10.10.0.31

[cs2]
cs01.staging.lanets.ca  ansible_host=10.110.0.101
cs02.staging.lanets.ca  ansible_host=10.110.0.102
cs03.staging.lanets.ca  ansible_host=10.110.0.103
cs04.staging.lanets.ca  ansible_host=10.110.0.104
cs05.staging.lanets.ca  ansible_host=10.110.0.105
cs06.staging.lanets.ca  ansible_host=10.110.0.106
cs07.staging.lanets.ca  ansible_host=10.110.0.107
cs08.staging.lanets.ca  ansible_host=10.110.0.108
cs09.staging.lanets.ca  ansible_host=10.110.0.109
cs10.staging.lanets.ca  ansible_host=10.110.0.110
cs11.staging.lanets.ca  ansible_host=10.110.0.111
cs12.staging.lanets.ca  ansible_host=10.110.0.112
cs13.staging.lanets.ca  ansible_host=10.110.0.113
cs14.staging.lanets.ca  ansible_host=10.110.0.114
cs15.staging.lanets.ca  ansible_host=10.110.0.115
cs16.staging.lanets.ca  ansible_host=10.110.0.116
cs17.staging.lanets.ca  ansible_host=10.110.0.117
cs18.staging.lanets.ca  ansible_host=10.110.0.118
cs19.staging.lanets.ca  ansible_host=10.110.0.119
cs20.staging.lanets.ca  ansible_host=10.110.0.120

[switches_event]
swm001.etsmtl.club ansible_host=10.0.21.195
swm002.etsmtl.club ansible_host=10.0.21.196
swm003.etsmtl.club ansible_host=10.0.21.197
swm004.etsmtl.club ansible_host=10.0.21.198
swm005.etsmtl.club ansible_host=10.0.21.199
swm006.etsmtl.club ansible_host=10.0.21.200
swm007.etsmtl.club ansible_host=10.0.21.201
swm008.etsmtl.club ansible_host=10.0.21.202
swm009.etsmtl.club ansible_host=10.0.21.203
swm010.etsmtl.club ansible_host=10.0.21.204
swm011.etsmtl.club ansible_host=10.0.21.205
swm012.etsmtl.club ansible_host=10.0.21.206
swm013.etsmtl.club ansible_host=10.0.21.207
swm014.etsmtl.club ansible_host=10.0.21.208
swm015.etsmtl.club ansible_host=10.0.21.209
swm016.etsmtl.club ansible_host=10.0.21.210
swm017.etsmtl.club ansible_host=10.0.21.211
swm018.etsmtl.club ansible_host=10.0.21.212
swm019.etsmtl.club ansible_host=10.0.21.213
swm020.etsmtl.club ansible_host=10.0.21.214
swm021.etsmtl.club ansible_host=10.0.21.215
swm022.etsmtl.club ansible_host=10.0.21.216
swm023.etsmtl.club ansible_host=10.0.21.217
swm024.etsmtl.club ansible_host=10.0.21.218
swm025.etsmtl.club ansible_host=10.0.21.219
swm026.etsmtl.club ansible_host=10.0.21.220
swm027.etsmtl.club ansible_host=10.0.21.221
swm028.etsmtl.club ansible_host=10.0.21.222
swm029.etsmtl.club ansible_host=10.0.21.223
swm030.etsmtl.club ansible_host=10.0.21.224
; swm031.etsmtl.club ansible_host=10.0.21.225
; swm032.etsmtl.club ansible_host=10.0.21.226
; swm033.etsmtl.club ansible_host=10.0.21.227
; swm034.etsmtl.club ansible_host=10.0.21.228
; swm035.etsmtl.club ansible_host=10.0.21.229
; swm036.etsmtl.club ansible_host=10.0.21.230
; swm037.etsmtl.club ansible_host=10.0.21.231
; swm038.etsmtl.club ansible_host=10.0.21.232
; swm039.etsmtl.club ansible_host=10.0.21.233
; swm040.etsmtl.club ansible_host=10.0.21.234
; swm041.etsmtl.club ansible_host=10.0.21.235
; swm042.etsmtl.club ansible_host=10.0.21.236
; swm043.etsmtl.club ansible_host=10.0.21.237
; swm044.etsmtl.club ansible_host=10.0.21.238
; swm045.etsmtl.club ansible_host=10.0.21.239
; swm046.etsmtl.club ansible_host=10.0.21.240
; swm047.etsmtl.club ansible_host=10.0.21.241
; swm048.etsmtl.club ansible_host=10.0.21.242
; swm049.etsmtl.club ansible_host=10.0.21.243
; swm050.etsmtl.club ansible_host=10.0.21.244
; swm051.etsmtl.club ansible_host=10.0.21.245
; swm052.etsmtl.club ansible_host=10.0.21.246
; swm053.etsmtl.club ansible_host=10.0.21.247
; swm054.etsmtl.club ansible_host=10.0.21.248
; swm055.etsmtl.club ansible_host=10.0.21.249
; swm056.etsmtl.club ansible_host=10.0.21.250
; swm057.etsmtl.club ansible_host=10.0.21.251
; swm058.etsmtl.club ansible_host=10.0.21.252
