---
- name: Provision Challenge VMs on Proxmox
  hosts: chall
  gather_facts: false
  become: false
  module_defaults:
    community.proxmox.proxmox_kvm:
      validate_certs: false
    community.proxmox.proxmox_disk:
      validate_certs: false
  roles:
    - cedille.proxmox.vm

- name: Install the docker role on this VM
  hosts: chall
  gather_facts: true
  become: true
  pre_tasks:
    - name: Wait for DNS to be functional
      ansible.builtin.command:
        cmd: nslookup archive.ubuntu.com
      retries: 10
      delay: 5
      register: dns_check
      until: dns_check.rc == 0
      changed_when: false
    - name: Configure apt proxy
      ansible.builtin.copy:
        content: 'Acquire::http::Proxy "http://{{ docker_registry_mirror_host }}:3142";'
        dest: /etc/apt/apt.conf.d/00proxy
        owner: root
        group: root
        mode: "0644"
      become: true
    - name: Configure pip proxy
      ansible.builtin.copy:
        content: |
          [global]
          index-url = http://{{ docker_registry_mirror_host }}:3141/root/pypi/+simple/
          trusted-host = {{ docker_registry_mirror_host }}
        dest: /etc/pip.conf
        owner: root
        group: root
        mode: "0644"
      become: true
  roles:
    - cedille.docker.install
  post_tasks:
    - name: Pull the latest images for the challenge
      community.docker.docker_compose_v2_pull:
        project_src: "{{ install_docker_compose_target_dir }}"
      register: pull_result
    - name: If images were pulled, recreate the containers
      community.docker.docker_compose_v2:
        project_src: "{{ install_docker_compose_target_dir }}"
        state: present
      when: pull_result.changed
