---
- name: Provision TFTP VMs on Proxmox
  hosts: netservices_tftp
  gather_facts: false
  become: false
  module_defaults:
    community.proxmox.proxmox_kvm:
      validate_certs: false
    community.proxmox.proxmox_disk:
      validate_certs: false
  roles:
    - cedille.proxmox.vm

- name: Wait for SSH on TFTP VMs
  hosts: netservices_tftp
  gather_facts: false
  tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        timeout: 120

- name: Deploy TFTP
  hosts: netservices_tftp
  gather_facts: true
  become: true
  vars_files:
    - ../../roles/kea/vars/flags.yml
  pre_tasks:
    - name: Configure apt proxy
      ansible.builtin.include_tasks: includes/apt_proxy.yaml
  roles:
    - tftp
