---
vm_id: 1003012
vm_name: k8s-cedille-sandbox-worker-2
vm_proxmox_node: pve06
vm_cpu_cores: 8
vm_memory_mb: 24576

vm_nets:
  - bridge: vmbr1
    vlan: 500
    mac: "BC:24:11:D0:0D:EA"
  - bridge: vmbr1
    vlan: 1003
    mac: "BC:24:11:94:72:02"
    ip: 10.10.1.167
    netmask: 25
  - bridge: vmbr1
    vlan: 247
    mac: "BC:24:11:02:06:A1"
