---
vm_id: 1010000
vm_name: k8s-cedille-production-v2-controlplane-0
vm_proxmox_node: pve03
vm_cpu_cores: 4
vm_memory_mb: 8192

vm_nets:
  - bridge: vmbr1
    vlan: 500
    mac: "BC:24:11:D9:07:EF"
  - bridge: vmbr1
    vlan: 1010
    mac: "BC:24:11:2F:E1:7C"
    ip: 10.5.10.48
    netmask: 24
