---
vm_id: 1009010
vm_name: k8s-shared-worker-0
vm_proxmox_node: pve01
# pve01 = tier "big" (1.2TiB/88 cores) → cible 24 cores / 64GB (RAM déjà à la cible).
vm_cpu_cores: 24
vm_memory_mb: 65536

vm_nets:
  - bridge: vmbr1
    vlan: 500
    mac: "BC:24:11:F2:BC:3B"
    ip: 10.5.9.13
    netmask: 24
  - bridge: vmbr1
    vlan: 1009
    mac: "BC:24:11:AC:B4:03"
    ip: 10.5.9.25
    netmask: 24
  - bridge: vmbr1
    vlan: 247
    mac: "BC:24:11:0F:A9:D1"
