---
vm_id: 1010015
vm_name: k8s-cedille-production-v2-worker-5
vm_proxmox_node: pve07
vm_cpu_cores: 8
vm_memory_mb: 24576

vm_nets:
  - bridge: vmbr1
    vlan: 500
    mac: "BC:24:11:5D:A5:19"
  - bridge: vmbr1
    vlan: 1010
    mac: "BC:24:11:23:01:52"
    ip: 10.5.10.50
    netmask: 24
  - bridge: vmbr1
    vlan: 247
    mac: "BC:24:11:86:FC:77"
