---
vm_id: 1010003
vm_name: k8s-cedille-production-v2-controlplane-3
vm_proxmox_node: pve07
vm_cpu_cores: 4
vm_memory_mb: 8192

vm_nets:
  - bridge: vmbr1
    vlan: 500
    mac: "BC:24:11:5F:BB:92"
  - bridge: vmbr1
    vlan: 1010
    mac: "BC:24:11:03:AA:94"
    ip: 10.5.10.45
    netmask: 24
