---
netservices_dhcp_network_octet: 110

vm_cpu_cores: 2
vm_memory_mb: 4096
vm_disk_size: 20G

vm_sshkeys: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcsmOTHd/jDJ9pn7J3XrhbiVTM5GFBc5LcQ8XPLBDS6 jumpbox.event.lanets.ca"

netservices_dhcp:
  enabled: true
  supported_distribution: Ubuntu
  supported_distribution_version: "24.04"

  install:
    update_cache: true
    package_state: present
    packages:
      - kea-dhcp4-server
      - kea-ctrl-agent

  service:
    dhcp4_name: kea-dhcp4-server
    ctrl_agent_name: kea-ctrl-agent
    state: started
    enabled: true

  paths:
    dhcp4_config: /etc/kea/kea-dhcp4.conf
    ctrl_agent_config: /etc/kea/kea-ctrl-agent.conf
    dhcp4_control_socket: /run/kea/kea4-ctrl-socket

  ha:
    enabled: true
    mode: hot-standby
    this_server_name: "{{ 'primary' if inventory_hostname.startswith('dhcp01') else 'secondary' }}"
    heartbeat_delay: 10000
    max_response_delay: 60000
    max_ack_delay: 5000
    max_unacked_clients: 10
    sync_page_limit: 10000
    primary:
      name: primary
      url: "http://10.{{ netservices_dhcp_network_octet }}.0.11:8000/"
    secondary:
      name: secondary
      url: "http://10.{{ netservices_dhcp_network_octet }}.0.12:8000/"

  kea_dhcp4_config:
    Dhcp4:
      interfaces-config:
        interfaces:
          - "*"
      control-socket:
        socket-type: unix
        socket-name: /run/kea/kea4-ctrl-socket
      lease-database:
        type: memfile
        persist: true
        name: /var/lib/kea/kea-leases4.csv
      valid-lifetime: 4000
      renew-timer: 1000
      rebind-timer: 2000
      subnet4:
        - subnet: "10.{{ netservices_dhcp_network_octet }}.0.0/16"
          id: "{{ netservices_dhcp_network_octet }}"
          pools:
            - pool: "10.{{ netservices_dhcp_network_octet }}.1.0 - 10.{{ netservices_dhcp_network_octet }}.16.255"
          reservations: "{{ lookup('pipe', 'python3 ' ~ playbook_dir ~ '/../../scripts/generate_dhcp_reservations.py') | from_yaml }}"
          option-data:
            - name: domain-name-servers
              data: "10.{{ netservices_dhcp_network_octet }}.0.21,10.{{ netservices_dhcp_network_octet }}.0.22,1.1.1.1"
            - name: domain-name
              data: event.lanets.ca
            - name: routers
              data: "10.{{ netservices_dhcp_network_octet }}.0.1"
      option-data: []
      hooks-libraries:
        - library: /usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_ha.so
          parameters:
            high-availability:
              this-server-name: "{{ 'primary' if inventory_hostname.startswith('dhcp01') else 'secondary' }}"
              mode: hot-standby
              heartbeat-delay: 10000
              max-response-delay: 60000
              max-ack-delay: 5000
              max-unacked-clients: 10
              sync-page-limit: 10000
              peers:
                - name: primary
                  url: "http://10.{{ netservices_dhcp_network_octet }}.0.11:8000/"
                  role: primary
                  auto-failover: true
                - name: secondary
                  url: "http://10.{{ netservices_dhcp_network_octet }}.0.12:8000/"
                  role: secondary
                  auto-failover: true
      loggers:
        - name: kea-dhcp4
          output_options:
            - output: stdout
          severity: INFO

  kea_ctrl_agent_config:
    Control-agent:
      http-host: 0.0.0.0
      http-port: 8000
      control-sockets:
        dhcp4:
          socket-type: unix
          socket-name: /run/kea/kea4-ctrl-socket
