---

- name: Deploying cs2 server
  hosts: cs2
  tasks:
    - name: Installing prerequise for cs2 server deployment
      ansible.builtin.include_role:
        name: lanets.cs2.deployment_prerequisites
    - name: Deploying cs2 server
      ansible.builtin.include_role:
        name: lanets.cs2.deploy_server
