---
vm_id: 3302
vm_name: dhcp02-330-event
vm_net:
  bridge: vmbr1
  vlan: 330
  device: virtio
  ip: 10.130.0.12
  netmask: 16
  gateway: 10.130.0.1
  nameservers: 1.1.1.1,8.8.8.8
  search_domain: event.lanets.ca
