---
vm_id: 3202
vm_name: dhcp02-320-event
vm_net:
  bridge: vmbr1
  vlan: 320
  device: virtio
  ip: 10.120.0.12
  netmask: 16
  gateway: 10.120.0.1
  nameservers: 1.1.1.1,8.8.8.8
  search_domain: event.lanets.ca
