---
vm_id: 4202
vm_name: dns02-320-event
vm_net:
  bridge: vmbr1
  vlan: 320
  device: virtio
  ip: 10.120.0.22
  netmask: 16
  gateway: 10.120.0.1
  nameservers: 1.1.1.1,8.8.8.8
  search_domain: event.lanets.ca
