---
vm_id: 4101
vm_name: dns01-66-event
vm_net:
  bridge: vmbr1
  vlan: 66
  device: virtio
  ip: 10.110.0.21
  netmask: 16
  gateway: 10.110.0.1
  nameservers: 1.1.1.1,8.8.8.8
  search_domain: event.lanets.ca
