---
vm_id: 4301
vm_name: dns01-68-event
vm_net:
  bridge: vmbr1
  vlan: 68
  device: virtio
  ip: 10.130.0.21
  netmask: 16
  gateway: 10.130.0.1
  nameservers: 1.1.1.1,8.8.8.8
  search_domain: event.lanets.ca
