---
# Déploie le serveur CS2 complet (prérequis système + server) sur la VM cs2 (LanETS).
# Hôtes : cs2

- name: Deploying cs2 server
  hosts: cs2
  tasks:
    - name: Installing prerequise for cs2 server deployment
      ansible.builtin.include_role:
        name: lanets.cs2.deployment_prerequisites
    - name: Deploying cs2 server
      ansible.builtin.include_role:
        name: lanets.cs2.deploy_server
